"$schema" = "schemas/schema.json"

[[permission]]
identifier = "allow-invoke"
description = "Enables all manual custom backend command invocations."
commands.allow = [
    "play_notification_sound",
    "create_notification_window",
    "close_notification_window",
    "upload_file_stream"
]
