"$schema" = "schemas/schema.json"

[[permission]]
identifier = "allow-invoke"
description = "Enables all manual custom backend command invocations."
commands.allow = [
    "play_notification_sound",
    "create_notification_window",
    "close_notification_window",
    "has_notification_window",
    "show_main_window",
    "open_settings_window",
    "get_settings",
    "save_settings",
    "upload_file_stream",
    "set_tray_alert"
]
