name: Build Windows
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Instalacja Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalacja zaleznosci frontendowych
        run: npm install

      - name: Instalacja środowiska Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Kompilacja Tauri (Tworzenie MSI)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          includeRelease: false

      - name: Wystawienie instalatora do pobrania
        uses: actions/upload-artifact@v4
        with:
          name: Google-Chat-Windows
          path: |
            src-tauri/target/**/bundle/**/*.exe
            src-tauri/target/**/bundle/**/*.msi
